// React/src/App.js
import {
  ColumnDirective,
  ColumnsDirective,
  Inject,
  TreeGridComponent,
} from '@syncfusion/ej2-react-treegrid';
import { Page } from '@syncfusion/ej2-react-treegrid';
import * as React from 'react';
import './App.css';
import { sampleData } from './datasource';
export default class App extends React.Component {
  checkboxChange(args) {
    if (args.checked) {
      setTimeout(() => {
        const checkedRows = this.element.querySelectorAll('.e-check');
        Array.from(checkedRows).map((row) => {
          row.closest('tr').classList.add('bgcolor');
        });
      }, 0);
    } else {
      setTimeout(() => {
        const coloredRows = this.element.querySelectorAll('.bgcolor');

        Array.from(coloredRows).map((row) => {
          if (row.querySelector('.e-uncheck') || row.querySelector('.e-stop')) {
            row.classList.remove('bgcolor');
          }
        });
      }, 0);
    }
  }
  render() {
    return (
      <TreeGridComponent
        dataSource={sampleData}
        treeColumnIndex={1}
        childMapping="subtasks"
        enableCollapseAll="true"
        autoCheckHierarchy="true"
        checkboxChange={this.checkboxChange}
      >
        <ColumnsDirective>
          <ColumnDirective
            field="taskID"
            headerText="Task ID"
            width="90"
            textAlign="Right"
          />
          <ColumnDirective
            field="taskName"
            showCheckbox="true"
            headerText="Task Name"
            width="180"
          />
          <ColumnDirective
            field="startDate"
            headerText="Start Date"
            width="90"
            format="yMd"
            textAlign="Right"
            type="date"
          />
          <ColumnDirective
            field="duration"
            headerText="Duration"
            width="80"
            textAlign="Right"
          />
        </ColumnsDirective>
        <Inject services={[Page]} />
      </TreeGridComponent>
    );
  }
}

// Angular/src/app/app.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { sampleData } from './jsontreegriddata';
import {
  TreeGridComponent,
  PageService,
} from '@syncfusion/ej2-angular-treegrid';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  providers: [PageService],
})
export class AppComponent {
  public data: Object[] = [];
  @ViewChild('treegrid')
  public treegrid!: TreeGridComponent;

  ngOnInit(): void {
    this.data = sampleData;
    // this.selectionsettings = { persistSelection: true
  }

  checkboxChange(args:any) {
    debugger;
    if (args.checked) {
      setTimeout(() => {
        const checkedRows = this.treegrid.element.querySelectorAll('.e-check');
        Array.from(checkedRows).map((row) => {
          row?.closest('tr')?.classList.add('bgcolor');
        });
      }, 0);
    } else {
      setTimeout(() => {
        const coloredRows = this.treegrid.element.querySelectorAll('.bgcolor');

        Array.from(coloredRows).map((row) => {
          if (row.querySelector('.e-uncheck') || row.querySelector('.e-stop')) {
            row.classList.remove('bgcolor');
          }
        });
      }, 0);
    }
  }
 
}

<div class="control-section">
  <ejs-treegrid
    #treegrid
    [dataSource]="data"
    height="350"
    enableCollapseAll="true"
    autoCheckHierarchy="true"
    childMapping="subtasks"
    [treeColumnIndex]="1"
    (checkboxChange)="checkboxChange($event)"
  >
    <e-columns>
      <e-column
        field="taskID"
        headerText="Task ID"
        isPrimaryKey="true"
        width="70"
        textAlign="Right"
      ></e-column>
      <e-column
        field="taskName"
        headerText="Task Name"
        width="200"
        [showCheckbox]="true"
      ></e-column>
    </e-columns>
  </ejs-treegrid>
</div>
